/// Flutter icons IconsVteme
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsVteme
///      fonts:
///       - asset: fonts/IconsVteme.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconsVteme {
  IconsVteme._();

  static const _kFontFam = 'IconsVteme';
  static const _kFontPkg = null;

  static const IconData entertainment = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_points = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartbeat = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hostel = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_announcements = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notebook = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_selected = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData services = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData services_selected = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi_selected = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tourism = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trade = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcements = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_selected = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notebook_selected = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
